DotNetCoreProject_Sayed/Models/Tourist.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace DotNetCoreProject_Sayed.Models
{
    [Table("Tourist")]
    public class Tourist
    {
        [Key]
        public long Id { get; set; }

        [Required, Display(Name = "Tourist")]
        public string Name { get; set; }

        public virtual IList<Order> Orders { get; set; }
    }
}

DotNetCoreProject_Sayed/Controllers/TouristsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DotNetCoreProject_Sayed.Data;
using DotNetCoreProject_Sayed.Models;

namespace DotNetCoreProject_Sayed.Controllers
{
    public class TouristsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public readonly IHostingEnvironment _hostingEnvironment;

        public TouristsController(ApplicationDbContext context, IHostingEnvironment hostingEnvironment)
        {
            _context = context;
            _hostingEnvironment = hostingEnvironment;
        }
        public async Task<ActionResult> Index()
        {
            ViewBag.CategoryID = new SelectList(_context.Tourists, "Id", "Name");
            return View(await _context.Tourists.ToListAsync());
        }
        public ActionResult TouristOrder(long? id)
        {
            if (id == null)
            {
                NotFound();
            }

            ViewData["id"] = id;
            List<Order> orders = _context.Orders.Where(e => e.TouristID == id).ToList();

            if (orders == null)
            {
                NotFound();
            }

            return PartialView("TouristOrder", orders);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Order orders, Tourist tourist, IFormFile[] Image)
        {
            try
            {

                if (Image != null)
                {
                    if (tourist.Orders.Count == Image.Count())
                    {
                        for (int i = 0; i < tourist.Orders.Count; i++)
                        {

                            string picture = System.IO.Path.GetFileName(Image[i].FileName);
                            var file = picture;
                            var uploadFile = Path.Combine(_hostingEnvironment.WebRootPath, "images", picture);

                            using (MemoryStream ms = new MemoryStream())
                            {
                                Image[i].CopyTo(ms);
                                tourist.Orders[i].Image = ms.GetBuffer();
                            }
                        }
                    }
                    _context.Tourists.Add(tourist);
                    _context.SaveChanges();
                    TempData["id"] = tourist.Id;
                    return RedirectToAction("Index");
                }

                return View(tourist);
            }
            catch (Exception)
            {
                return View(tourist);
            }
        }

       
        public IActionResult Delete(long id)
        {
            Tourist tourist = _context.Tourists.Find(id);
            if (tourist != null)
            {
                _context.Tourists.Remove(tourist);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        public IActionResult DeleteItem(long id)
        {
            Order order = _context.Orders.Find(id);
            if (order != null)
            {
                _context.Orders.Remove(order);
                _context.SaveChanges();
                return RedirectToAction("Index");

            }
            return RedirectToAction("Index");
        }
    }
}

DotNetCoreProject_Sayed/Views/Tourists/Create.cshtml
@model DotNetCoreProject_Sayed.Models.Tourist

<form enctype="multipart/form-data" asp-controller="Tourists" asp-action="Create" method="post" class="mt-3">
    <div class="modal-header">
        <h5 class="modal-title" id="touristModalLabel">Add new tourist</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body" style="border:5px solid gray">
        <div class="form-group">
            Tourist Name:
            <input asp-for="Name" class="form-control" placeholder="Tourist Name" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div id="0">
            <hr />

            <div class="modal-body">
                <div class="form-group">
                    Food Name:
                    <input asp-for="Orders[0].Name" class="form-control" placeholder="Name of Food" />
                    <span asp-validation-for="Orders[0].Name" class="text-danger"></span>

                </div>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    Description :
                    <input asp-for="Orders[0].Description" class="form-control" />
                    <span asp-validation-for="Orders[0].Description" class="text-danger"></span>

                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-12">
                    Image :
                    <img id="_0" src="" width="300" data-tag="orderImageinTourist" />
                    <input id="Image" name="Image" type="file" data-tag="_0" onchange="changeImage(this, event)" />
                    <span asp-validation-for="Orders[0].Image" class="text-danger"></span>
                </div>

            </div>
            <br />
            <div class="row">
                <div class="form-group col-md-6">
                    Buying Date :
                    <input asp-for="Orders[0].BuyingDate" class="form-control" />
                    <span asp-validation-for="Orders[0].BuyingDate" class="text-danger"></span>
                </div>

                <div class="form-group col-md-6">
                    Quantity :
                    <input asp-for="Orders[0].Quantity" class="form-control" />
                    <span asp-validation-for="Orders[0].Quantity" class="text-danger"></span>
                </div>
            </div>
        </div>
        <hr />
        <div class="col-md-12">
            <button id="addModelButton" type="button" class="btn btn-dark btn-block">Add Orders</button>
        </div>
        <input id="sl" type="hidden" value="0" />
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <input type="submit" class="btn btn-primary" value="Save" />
    </div>
</form>

DotNetCoreProject_Sayed/Views/Tourists/Index.cshtml
@model IEnumerable<DotNetCoreProject_Sayed.Models.Tourist>
@{ ViewBag.Title = "Index"; }
<div class="row">
    @*<div class="Col-md-8" style="margin-top:4rem; margin-left:7rem;">
            <div id="orders">
            </div>
        </div>*@
    <div class="col-md-5">
        <br /><br /><br />
                    <div id="tourist" style="background-color:lightgoldenrodyellow">
                        <h2 style="text-align:center;">Tourist Informations</h2>
                        <p>
                            <button type="button" class="btn btn-outline-secondary btn-lg" data-toggle="modal" data-target="#touristModal">Create New Tourist With Product</button>
                        </p>
                        @foreach (var item in Model)
                        {
                            <table class="table table-bordered table-hover table-striped" style="text-align:center;">
                                <tr>
                                    <th>Tourist Name</th>
                                    <th>Action</th>
                                </tr>
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Name)
                                    </td>
                                    <td>
                                        <button class="btn btn-info" onclick="getDetails(@item.Id)">Details</button>&nbsp;&nbsp;
                                        <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
                                    </td>
                                </tr>
                            </table>
                        }
                    </div>
    </div>
    <div class="Col-md-9" style="margin-top:5rem; margin-left:8rem; background-color:lightgoldenrodyellow">
        <div id="orders">
        </div>
    </div>
</div>
<div class="modal fade" id="touristModal" tabindex="-1" aria-labelledby="touristModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            @{ Html.RenderPartialAsync("Create", new DotNetCoreProject_Sayed.Models.Tourist()); }
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $("#tourist").height($(window).height() * .80);
            $("#orders").height($(window).height() * .70);
            if (isNaN(@TempData["id"]) == false) {
                var link = '@Url.Action("TouristOrder", "Tourists", new { id = @TempData["id"] })';
                $("#orders").load(link);
            }
            $('#touristModal').on('shown.bs.modal', function () {
                $('#Name').trigger('focus');
            });
            $('#touristModal').on('hidden.bs.modal', function (event) {
                $("input[type=text]").val("");
                $("input[type=number]").val("");
                $("input[type=datetime-local]").val("");
                $('#sl').val('0');
                $("div").each(function () {
                    if (parseInt(this.id) > 0) {
                        this.remove();
                    }
                })
            });
            $('#addModelButton').on('click', function () {
                var present_sl = parseInt($('#sl').val());
                var next_sl = parseInt(present_sl) + 1;
                var next_item = '<div id="' + next_sl + '">' + $('#' + present_sl).html() + '</div>';
                next_item = next_item.split('_' + present_sl.toString()).join('_' + next_sl.toString());
                next_item = next_item.split('[' + present_sl.toString() + ']').join('[' + next_sl.toString() + ']');
                $('#' + present_sl).after(next_item);
                $('#sl').val(next_sl);
            });
            $('#orderModal').on('hidden.bs.modal', function (event) {
                $("input[type=text]").val("");
                $("input[type=number]").val("");
                $("input[type=datetime-local]").val("");
            });
        });
        function getDetails(e) {
            var link = '@Url.Action("TouristOrder", "Tourists", new { id = "-1" })';
            link = link.replace("-1", e);
            $("#orders").load(link);
        }
        var loadImage = function (event) {
            if (event.target.files && event.target.files[0]) {
                var img = document.getElementById('orderImage');
                img.src = URL.createObjectURL(event.target.files[0]);
            }
        }
        var changeImage = function (obj, event) {
            if (event.target.files && event.target.files[0]) {
                console.log(obj.dataset.tag);
                var img = document.getElementById(obj.dataset.tag);
                img.src = URL.createObjectURL(event.target.files[0]);
            }
        }
    </script>
}

DotNetCoreProject_Sayed/Views/Tourists/TouristOrder.cshtml
@model IEnumerable<DotNetCoreProject_Sayed.Models.Order>

<h2 style="text-align:center;">List Of This Order</h2>


<table class="table table-bordered table-hover table-striped justify-content-center">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.BuyingDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>Action</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>

                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.BuyingDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                <a asp-action="DeleteItem" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
            </td>
        </tr>
    }

</table>