DotNetCoreProject_Sayed/Controllers/BookingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DotNetCoreProject_Sayed.Data;
using DotNetCoreProject_Sayed.Interface;
//using DotNetCoreProject_Sayed.Interfaces;
using DotNetCoreProject_Sayed.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DotNetCoreProject_Sayed.Controllers
{
    public class BookingController : Controller
    {
        private IBookingRepository db;

        private ICustomerRepository db2;

        private readonly ApplicationDbContext _context;


        public BookingController(IBookingRepository db, ICustomerRepository db2, ApplicationDbContext _context)
        {
            this.db = db;
            this.db2 = db2;

            this._context = _context;
        }
        public IActionResult Index()
        {            
            var applicationDbContext = _context.Customers.ToList();

            return View(db.GetAll());
        }
        
        // GET:Create
        public IActionResult Create()
        {
            ViewBag.CustomerId = db2.GetAll();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Booking booking)
        {
            ViewBag.CustomerId = db2.GetAll();
            db.Add(booking);
            return RedirectToAction("Index");

        }

        public IActionResult Delete(int id)
        {
            db.Delete(id);
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            var applicationDbContext = _context.Bookings.ToList();
            ViewBag.CustomerId = db2.GetAll();

            return View(db.GetBooking(id));
        }

        [HttpPost]
        public IActionResult Edit(Booking booking)
        {
            ViewBag.CustomerId = db2.GetAll();
            db.Update(booking);
            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            return View(db.GetBooking(id));
        }
    }
}

DotNetCoreProject_Sayed/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DotNetCoreProject_Sayed.Interface;
using DotNetCoreProject_Sayed.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DotNetCoreProject_Sayed.Controllers
{
    public class CustomerController : Controller
    {

        private ICustomerRepository db;

        public CustomerController(ICustomerRepository db)
        {
            this.db = db;
        }
        public IActionResult Index()
        {
            return View(db.GetAll());
        }



        // GET:Create
        [Authorize(Policy = "CreateRolePolicy")]

        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Customer customer)
        {

            db.Add(customer);
            return RedirectToAction("Index");

        }
        [Authorize(Policy = "DeleteRolePolicy")]

        public IActionResult Delete(int id)
        {
            db.Delete(id);
            return RedirectToAction("Index");
        }

        [Authorize(Policy = "EditRolePolicy")]

        public IActionResult Edit(int id)
        {
            return View(db.GetCustomer(id));
        }

        [HttpPost]
        public IActionResult Edit(Customer customer)
        {
            db.Update(customer);
            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            return View(db.GetCustomer(id));
        }

    }
}

DotNetCoreProject_Sayed/Controllers/RoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DotNetCoreProject_Sayed.Data;
using DotNetCoreProject_Sayed.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using static DotNetCoreProject_Sayed.Helper;

namespace DotNetCoreProject_Sayed.Controllers
{
    public class RoomController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RoomController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _context.Rooms.ToListAsync());
        }
        [NoDirectAccess]
        public async Task<IActionResult> AddOrEdit(int id = 0)
        {
            if (id == 0)
                return View(new Room());
            else
            {
                var RoomModel = await _context.Rooms.FindAsync(id);
                if (RoomModel == null)
                {
                    return NotFound();
                }
                return View(RoomModel);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit(int id, [Bind("RoomId,RoomNumber,AreaName,HotelName,SecurityCode,Cost,BookingDate")] Room RoomModel)
        {
            if (ModelState.IsValid)
            {
                if (id == 0)
                {
                   // RoomModel.BookingDate = DateTime.Now;
                    _context.Add(RoomModel);
                    await _context.SaveChangesAsync();

                }
                else
                {
                    try
                    {
                        _context.Update(RoomModel);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!RoomModelExists(RoomModel.RoomId))
                        { return NotFound(); }
                        else
                        { throw; }
                    }
                }
                return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "_ViewAll", _context.Rooms.ToList()) });
            }
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "AddOrEdit", RoomModel) });
        }
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var RoomModel = await _context.Rooms
                .FirstOrDefaultAsync(m => m.RoomId == id);
            if (RoomModel == null)
            {
                return NotFound();
            }

            return View(RoomModel);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var RoomModel = await _context.Rooms.FindAsync(id);
            _context.Rooms.Remove(RoomModel);
            await _context.SaveChangesAsync();
            return Json(new { html = Helper.RenderRazorViewToString(this, "_ViewAll", _context.Rooms.ToList()) });
        }

        private bool RoomModelExists(int id)
        {
            return _context.Rooms.Any(e => e.RoomId == id);
        }
    }
}

DotNetCoreProject_Sayed/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DotNetCoreProject_Sayed</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DotNetCoreProject_Sayed</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @*<partial name="_LoginPartial" />*@
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Booking" asp-action="Index">Booking</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Room" asp-action="Index">Room</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FoodItem" asp-action="Index">FoodItem</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tourists" asp-action="Index">Tourist</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Administration" asp-action="ListRoles">List Role</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Administration" asp-action="ListUsers">List User</a>
                        </li>

                        <ul class="nav navbar-nav">
                            @if (SignInManager.IsSignedIn(User))
                            {
                                <li class="nav-item">
                                    <form method="post" asp-controller="account" asp-action="logout">
                                        <button type="submit" style="width:auto"
                                                class="nav-link btn btn-link py-0">
                                            Logout @User.Identity.Name
                                        </button>
                                    </form>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="account" asp-action="register">
                                        Register
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="account" asp-action="login">
                                        Login
                                    </a>
                                </li>
                            }
                        </ul>


                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - DotNetCoreProject_Sayed - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>